//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATN.Crawler.WokSearch {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class InternalServerException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class citedReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string articleIDField;
        
        private string citedAuthorField;
        
        private string citedTitleField;
        
        private string citedWorkField;
        
        private string pageField;
        
        private string recIDField;
        
        private string refIDField;
        
        private string timesCitedField;
        
        private string volumeField;
        
        private string yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string articleID {
            get {
                return this.articleIDField;
            }
            set {
                this.articleIDField = value;
                this.RaisePropertyChanged("articleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string citedAuthor {
            get {
                return this.citedAuthorField;
            }
            set {
                this.citedAuthorField = value;
                this.RaisePropertyChanged("citedAuthor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string citedTitle {
            get {
                return this.citedTitleField;
            }
            set {
                this.citedTitleField = value;
                this.RaisePropertyChanged("citedTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string citedWork {
            get {
                return this.citedWorkField;
            }
            set {
                this.citedWorkField = value;
                this.RaisePropertyChanged("citedWork");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string recID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("recID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string refID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
                this.RaisePropertyChanged("refID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string timesCited {
            get {
                return this.timesCitedField;
            }
            set {
                this.timesCitedField = value;
                this.RaisePropertyChanged("timesCited");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class keyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class queryField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string sortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
                this.RaisePropertyChanged("sort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class collectionFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string collectionNameField;
        
        private string[] fieldListField;
        
        private string listNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string collectionName {
            get {
                return this.collectionNameField;
            }
            set {
                this.collectionNameField = value;
                this.RaisePropertyChanged("collectionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] fieldList {
            get {
                return this.fieldListField;
            }
            set {
                this.fieldListField = value;
                this.RaisePropertyChanged("fieldList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string listName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
                this.RaisePropertyChanged("listName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class retrieveParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private collectionFields[] collectionFieldsField;
        
        private int countField;
        
        private queryField[] fieldsField;
        
        private int firstRecordField;
        
        private keyValuePair[] optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("collectionFields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public collectionFields[] collectionFields {
            get {
                return this.collectionFieldsField;
            }
            set {
                this.collectionFieldsField = value;
                this.RaisePropertyChanged("collectionFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public queryField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int firstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                this.firstRecordField = value;
                this.RaisePropertyChanged("firstRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public keyValuePair[] options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("options");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class InvalidInputException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class ESTIWSException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class AuthenticationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class QueryException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class SessionException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", ConfigurationName="WokSearch.WokSearch")]
    public interface WokSearch {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.citedReferencesRetrieveResponse citedReferencesRetrieve(ATN.Crawler.WokSearch.citedReferencesRetrieve request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citedReferencesRetrieveResponse> citedReferencesRetrieveAsync(ATN.Crawler.WokSearch.citedReferencesRetrieve request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.relatedRecordsResponse relatedRecords(ATN.Crawler.WokSearch.relatedRecords request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.relatedRecordsResponse> relatedRecordsAsync(ATN.Crawler.WokSearch.relatedRecords request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.citedReferencesResponse citedReferences(ATN.Crawler.WokSearch.citedReferences request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citedReferencesResponse> citedReferencesAsync(ATN.Crawler.WokSearch.citedReferences request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.retrieveResponse retrieve(ATN.Crawler.WokSearch.retrieve request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.retrieveResponse> retrieveAsync(ATN.Crawler.WokSearch.retrieve request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.searchResponse search(ATN.Crawler.WokSearch.search request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.searchResponse> searchAsync(ATN.Crawler.WokSearch.search request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.citingArticlesResponse citingArticles(ATN.Crawler.WokSearch.citingArticles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citingArticlesResponse> citingArticlesAsync(ATN.Crawler.WokSearch.citingArticles request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearch.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearch.retrieveByIdResponse retrieveById(ATN.Crawler.WokSearch.retrieveById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.retrieveByIdResponse> retrieveByIdAsync(ATN.Crawler.WokSearch.retrieveById request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citedReferencesRetrieve", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citedReferencesRetrieve {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public citedReferencesRetrieve() {
        }
        
        public citedReferencesRetrieve(string queryId, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.queryId = queryId;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citedReferencesRetrieveResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citedReferencesRetrieveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.citedReference[] @return;
        
        public citedReferencesRetrieveResponse() {
        }
        
        public citedReferencesRetrieveResponse(ATN.Crawler.WokSearch.citedReference[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class editionDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string collectionField;
        
        private string editionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string collection {
            get {
                return this.collectionField;
            }
            set {
                this.collectionField = value;
                this.RaisePropertyChanged("collection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
                this.RaisePropertyChanged("edition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class timeSpan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string beginField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
                this.RaisePropertyChanged("begin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class fullRecordSearchResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private labelValuesPair[] optionsField;
        
        private string parentField;
        
        private string queryIDField;
        
        private string recordsField;
        
        private int recordsFoundField;
        
        private long recordsSearchedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public labelValuesPair[] options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("options");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
                this.RaisePropertyChanged("parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string queryID {
            get {
                return this.queryIDField;
            }
            set {
                this.queryIDField = value;
                this.RaisePropertyChanged("queryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int recordsFound {
            get {
                return this.recordsFoundField;
            }
            set {
                this.recordsFoundField = value;
                this.RaisePropertyChanged("recordsFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long recordsSearched {
            get {
                return this.recordsSearchedField;
            }
            set {
                this.recordsSearchedField = value;
                this.RaisePropertyChanged("recordsSearched");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class labelValuesPair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="relatedRecords", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class relatedRecords {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.editionDesc[] editions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.timeSpan timeSpan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public relatedRecords() {
        }
        
        public relatedRecords(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uid = uid;
            this.editions = editions;
            this.timeSpan = timeSpan;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="relatedRecordsResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class relatedRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.fullRecordSearchResults @return;
        
        public relatedRecordsResponse() {
        }
        
        public relatedRecordsResponse(ATN.Crawler.WokSearch.fullRecordSearchResults @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class citedReferencesSearchResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queryIDField;
        
        private citedReference[] recordsField;
        
        private int recordsFoundField;
        
        private long recordsSearchedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string queryID {
            get {
                return this.queryIDField;
            }
            set {
                this.queryIDField = value;
                this.RaisePropertyChanged("queryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public citedReference[] records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int recordsFound {
            get {
                return this.recordsFoundField;
            }
            set {
                this.recordsFoundField = value;
                this.RaisePropertyChanged("recordsFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long recordsSearched {
            get {
                return this.recordsSearchedField;
            }
            set {
                this.recordsSearchedField = value;
                this.RaisePropertyChanged("recordsSearched");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citedReferences", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citedReferences {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.editionDesc[] editions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.timeSpan timeSpan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public citedReferences() {
        }
        
        public citedReferences(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uid = uid;
            this.editions = editions;
            this.timeSpan = timeSpan;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citedReferencesResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citedReferencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.citedReferencesSearchResults @return;
        
        public citedReferencesResponse() {
        }
        
        public citedReferencesResponse(ATN.Crawler.WokSearch.citedReferencesSearchResults @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class fullRecordData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private labelValuesPair[] optionsField;
        
        private string recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public labelValuesPair[] options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("options");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieve", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieve {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public retrieve() {
        }
        
        public retrieve(string queryId, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.queryId = queryId;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.fullRecordData @return;
        
        public retrieveResponse() {
        }
        
        public retrieveResponse(ATN.Crawler.WokSearch.fullRecordData @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com")]
    public partial class queryParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string databaseIDField;
        
        private editionDesc[] editionsField;
        
        private string queryLanguageField;
        
        private string symbolicTimeSpanField;
        
        private timeSpan timeSpanField;
        
        private string userQueryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string databaseID {
            get {
                return this.databaseIDField;
            }
            set {
                this.databaseIDField = value;
                this.RaisePropertyChanged("databaseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public editionDesc[] editions {
            get {
                return this.editionsField;
            }
            set {
                this.editionsField = value;
                this.RaisePropertyChanged("editions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string queryLanguage {
            get {
                return this.queryLanguageField;
            }
            set {
                this.queryLanguageField = value;
                this.RaisePropertyChanged("queryLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string symbolicTimeSpan {
            get {
                return this.symbolicTimeSpanField;
            }
            set {
                this.symbolicTimeSpanField = value;
                this.RaisePropertyChanged("symbolicTimeSpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public timeSpan timeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("timeSpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userQuery {
            get {
                return this.userQueryField;
            }
            set {
                this.userQueryField = value;
                this.RaisePropertyChanged("userQuery");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="search", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class search {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.queryParameters queryParameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public search() {
        }
        
        public search(ATN.Crawler.WokSearch.queryParameters queryParameters, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.queryParameters = queryParameters;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class searchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.fullRecordSearchResults @return;
        
        public searchResponse() {
        }
        
        public searchResponse(ATN.Crawler.WokSearch.fullRecordSearchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citingArticles", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citingArticles {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.editionDesc[] editions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.timeSpan timeSpan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public citingArticles() {
        }
        
        public citingArticles(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uid = uid;
            this.editions = editions;
            this.timeSpan = timeSpan;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citingArticlesResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citingArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.fullRecordSearchResults @return;
        
        public citingArticlesResponse() {
        }
        
        public citingArticlesResponse(ATN.Crawler.WokSearch.fullRecordSearchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveById", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieveById {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("uids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] uids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.retrieveParameters retrieveParameters;
        
        public retrieveById() {
        }
        
        public retrieveById(string databaseId, string[] uids, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uids = uids;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveByIdResponse", WrapperNamespace="http://woksearch.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieveByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearch.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearch.fullRecordSearchResults @return;
        
        public retrieveByIdResponse() {
        }
        
        public retrieveByIdResponse(ATN.Crawler.WokSearch.fullRecordSearchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WokSearchChannel : ATN.Crawler.WokSearch.WokSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WokSearchClient : System.ServiceModel.ClientBase<ATN.Crawler.WokSearch.WokSearch>, ATN.Crawler.WokSearch.WokSearch {
        
        public WokSearchClient() {
        }
        
        public WokSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WokSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WokSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WokSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.citedReferencesRetrieveResponse ATN.Crawler.WokSearch.WokSearch.citedReferencesRetrieve(ATN.Crawler.WokSearch.citedReferencesRetrieve request) {
            return base.Channel.citedReferencesRetrieve(request);
        }
        
        public ATN.Crawler.WokSearch.citedReference[] citedReferencesRetrieve(string queryId, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.citedReferencesRetrieve inValue = new ATN.Crawler.WokSearch.citedReferencesRetrieve();
            inValue.queryId = queryId;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.citedReferencesRetrieveResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).citedReferencesRetrieve(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citedReferencesRetrieveResponse> ATN.Crawler.WokSearch.WokSearch.citedReferencesRetrieveAsync(ATN.Crawler.WokSearch.citedReferencesRetrieve request) {
            return base.Channel.citedReferencesRetrieveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citedReferencesRetrieveResponse> citedReferencesRetrieveAsync(string queryId, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.citedReferencesRetrieve inValue = new ATN.Crawler.WokSearch.citedReferencesRetrieve();
            inValue.queryId = queryId;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).citedReferencesRetrieveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.relatedRecordsResponse ATN.Crawler.WokSearch.WokSearch.relatedRecords(ATN.Crawler.WokSearch.relatedRecords request) {
            return base.Channel.relatedRecords(request);
        }
        
        public ATN.Crawler.WokSearch.fullRecordSearchResults relatedRecords(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.relatedRecords inValue = new ATN.Crawler.WokSearch.relatedRecords();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editions = editions;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.relatedRecordsResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).relatedRecords(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.relatedRecordsResponse> ATN.Crawler.WokSearch.WokSearch.relatedRecordsAsync(ATN.Crawler.WokSearch.relatedRecords request) {
            return base.Channel.relatedRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.relatedRecordsResponse> relatedRecordsAsync(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.relatedRecords inValue = new ATN.Crawler.WokSearch.relatedRecords();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editions = editions;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).relatedRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.citedReferencesResponse ATN.Crawler.WokSearch.WokSearch.citedReferences(ATN.Crawler.WokSearch.citedReferences request) {
            return base.Channel.citedReferences(request);
        }
        
        public ATN.Crawler.WokSearch.citedReferencesSearchResults citedReferences(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.citedReferences inValue = new ATN.Crawler.WokSearch.citedReferences();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editions = editions;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.citedReferencesResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).citedReferences(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citedReferencesResponse> ATN.Crawler.WokSearch.WokSearch.citedReferencesAsync(ATN.Crawler.WokSearch.citedReferences request) {
            return base.Channel.citedReferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citedReferencesResponse> citedReferencesAsync(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.citedReferences inValue = new ATN.Crawler.WokSearch.citedReferences();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editions = editions;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).citedReferencesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.retrieveResponse ATN.Crawler.WokSearch.WokSearch.retrieve(ATN.Crawler.WokSearch.retrieve request) {
            return base.Channel.retrieve(request);
        }
        
        public ATN.Crawler.WokSearch.fullRecordData retrieve(string queryId, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.retrieve inValue = new ATN.Crawler.WokSearch.retrieve();
            inValue.queryId = queryId;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.retrieveResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).retrieve(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.retrieveResponse> ATN.Crawler.WokSearch.WokSearch.retrieveAsync(ATN.Crawler.WokSearch.retrieve request) {
            return base.Channel.retrieveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.retrieveResponse> retrieveAsync(string queryId, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.retrieve inValue = new ATN.Crawler.WokSearch.retrieve();
            inValue.queryId = queryId;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).retrieveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.searchResponse ATN.Crawler.WokSearch.WokSearch.search(ATN.Crawler.WokSearch.search request) {
            return base.Channel.search(request);
        }
        
        public ATN.Crawler.WokSearch.fullRecordSearchResults search(ATN.Crawler.WokSearch.queryParameters queryParameters, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.search inValue = new ATN.Crawler.WokSearch.search();
            inValue.queryParameters = queryParameters;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.searchResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).search(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.searchResponse> ATN.Crawler.WokSearch.WokSearch.searchAsync(ATN.Crawler.WokSearch.search request) {
            return base.Channel.searchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.searchResponse> searchAsync(ATN.Crawler.WokSearch.queryParameters queryParameters, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.search inValue = new ATN.Crawler.WokSearch.search();
            inValue.queryParameters = queryParameters;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).searchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.citingArticlesResponse ATN.Crawler.WokSearch.WokSearch.citingArticles(ATN.Crawler.WokSearch.citingArticles request) {
            return base.Channel.citingArticles(request);
        }
        
        public ATN.Crawler.WokSearch.fullRecordSearchResults citingArticles(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.citingArticles inValue = new ATN.Crawler.WokSearch.citingArticles();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editions = editions;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.citingArticlesResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).citingArticles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citingArticlesResponse> ATN.Crawler.WokSearch.WokSearch.citingArticlesAsync(ATN.Crawler.WokSearch.citingArticles request) {
            return base.Channel.citingArticlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.citingArticlesResponse> citingArticlesAsync(string databaseId, string uid, ATN.Crawler.WokSearch.editionDesc[] editions, ATN.Crawler.WokSearch.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.citingArticles inValue = new ATN.Crawler.WokSearch.citingArticles();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editions = editions;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).citingArticlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearch.retrieveByIdResponse ATN.Crawler.WokSearch.WokSearch.retrieveById(ATN.Crawler.WokSearch.retrieveById request) {
            return base.Channel.retrieveById(request);
        }
        
        public ATN.Crawler.WokSearch.fullRecordSearchResults retrieveById(string databaseId, string[] uids, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.retrieveById inValue = new ATN.Crawler.WokSearch.retrieveById();
            inValue.databaseId = databaseId;
            inValue.uids = uids;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearch.retrieveByIdResponse retVal = ((ATN.Crawler.WokSearch.WokSearch)(this)).retrieveById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearch.retrieveByIdResponse> ATN.Crawler.WokSearch.WokSearch.retrieveByIdAsync(ATN.Crawler.WokSearch.retrieveById request) {
            return base.Channel.retrieveByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearch.retrieveByIdResponse> retrieveByIdAsync(string databaseId, string[] uids, string queryLanguage, ATN.Crawler.WokSearch.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearch.retrieveById inValue = new ATN.Crawler.WokSearch.retrieveById();
            inValue.databaseId = databaseId;
            inValue.uids = uids;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearch.WokSearch)(this)).retrieveByIdAsync(inValue);
        }
    }
}
