//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IN3LP_TestModel", "fk_Source_Author", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AdjacencyMatrixBuild.Author), "Source", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdjacencyMatrixBuild.Source), true)]
[assembly: EdmRelationshipAttribute("IN3LP_TestModel", "fk_Source_Editor", "Editor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AdjacencyMatrixBuild.Editor), "Source", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdjacencyMatrixBuild.Source), true)]
[assembly: EdmRelationshipAttribute("IN3LP_TestModel", "fk_Source_Journal", "Journal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AdjacencyMatrixBuild.Journal), "Source", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdjacencyMatrixBuild.Source), true)]
[assembly: EdmRelationshipAttribute("IN3LP_TestModel", "CitationReference", "Source", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdjacencyMatrixBuild.Source), "Source1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdjacencyMatrixBuild.Source))]

#endregion

namespace AdjacencyMatrixBuild
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IN3LP_TestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IN3LP_TestEntities object using the connection string found in the 'IN3LP_TestEntities' section of the application configuration file.
        /// </summary>
        public IN3LP_TestEntities() : base("name=IN3LP_TestEntities", "IN3LP_TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IN3LP_TestEntities object.
        /// </summary>
        public IN3LP_TestEntities(string connectionString) : base(connectionString, "IN3LP_TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IN3LP_TestEntities object.
        /// </summary>
        public IN3LP_TestEntities(EntityConnection connection) : base(connection, "IN3LP_TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Editor> Editors
        {
            get
            {
                if ((_Editors == null))
                {
                    _Editors = base.CreateObjectSet<Editor>("Editors");
                }
                return _Editors;
            }
        }
        private ObjectSet<Editor> _Editors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Journal> Journals
        {
            get
            {
                if ((_Journals == null))
                {
                    _Journals = base.CreateObjectSet<Journal>("Journals");
                }
                return _Journals;
            }
        }
        private ObjectSet<Journal> _Journals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Source> Sources
        {
            get
            {
                if ((_Sources == null))
                {
                    _Sources = base.CreateObjectSet<Source>("Sources");
                }
                return _Sources;
            }
        }
        private ObjectSet<Source> _Sources;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Editors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEditors(Editor editor)
        {
            base.AddObject("Editors", editor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Journals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJournals(Journal journal)
        {
            base.AddObject("Journals", journal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSources(Source source)
        {
            base.AddObject("Sources", source);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN3LP_TestModel", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="authorId">Initial value of the AuthorId property.</param>
        public static Author CreateAuthor(global::System.Int32 authorId)
        {
            Author author = new Author();
            author.AuthorId = authorId;
            return author;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                if (_AuthorId != value)
                {
                    OnAuthorIdChanging(value);
                    ReportPropertyChanging("AuthorId");
                    _AuthorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuthorId");
                    OnAuthorIdChanged();
                }
            }
        }
        private global::System.Int32 _AuthorId;
        partial void OnAuthorIdChanging(global::System.Int32 value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> AuthorsOrder
        {
            get
            {
                return _AuthorsOrder;
            }
            set
            {
                OnAuthorsOrderChanging(value);
                ReportPropertyChanging("AuthorsOrder");
                _AuthorsOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorsOrder");
                OnAuthorsOrderChanged();
            }
        }
        private Nullable<global::System.Int16> _AuthorsOrder;
        partial void OnAuthorsOrderChanging(Nullable<global::System.Int16> value);
        partial void OnAuthorsOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramId
        {
            get
            {
                return _ProgramId;
            }
            set
            {
                OnProgramIdChanging(value);
                ReportPropertyChanging("ProgramId");
                _ProgramId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramId");
                OnProgramIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramId;
        partial void OnProgramIdChanging(Nullable<global::System.Int32> value);
        partial void OnProgramIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "fk_Source_Author", "Source")]
        public EntityCollection<Source> Sources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Source>("IN3LP_TestModel.fk_Source_Author", "Source");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Source>("IN3LP_TestModel.fk_Source_Author", "Source", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN3LP_TestModel", Name="Editor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Editor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Editor object.
        /// </summary>
        /// <param name="editorId">Initial value of the EditorId property.</param>
        public static Editor CreateEditor(global::System.Int32 editorId)
        {
            Editor editor = new Editor();
            editor.EditorId = editorId;
            return editor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EditorId
        {
            get
            {
                return _EditorId;
            }
            set
            {
                if (_EditorId != value)
                {
                    OnEditorIdChanging(value);
                    ReportPropertyChanging("EditorId");
                    _EditorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EditorId");
                    OnEditorIdChanged();
                }
            }
        }
        private global::System.Int32 _EditorId;
        partial void OnEditorIdChanging(global::System.Int32 value);
        partial void OnEditorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> EditorsOrder
        {
            get
            {
                return _EditorsOrder;
            }
            set
            {
                OnEditorsOrderChanging(value);
                ReportPropertyChanging("EditorsOrder");
                _EditorsOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditorsOrder");
                OnEditorsOrderChanged();
            }
        }
        private Nullable<global::System.Int16> _EditorsOrder;
        partial void OnEditorsOrderChanging(Nullable<global::System.Int16> value);
        partial void OnEditorsOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramId
        {
            get
            {
                return _ProgramId;
            }
            set
            {
                OnProgramIdChanging(value);
                ReportPropertyChanging("ProgramId");
                _ProgramId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramId");
                OnProgramIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramId;
        partial void OnProgramIdChanging(Nullable<global::System.Int32> value);
        partial void OnProgramIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "fk_Source_Editor", "Source")]
        public EntityCollection<Source> Sources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Source>("IN3LP_TestModel.fk_Source_Editor", "Source");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Source>("IN3LP_TestModel.fk_Source_Editor", "Source", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN3LP_TestModel", Name="Journal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Journal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Journal object.
        /// </summary>
        /// <param name="journalId">Initial value of the JournalId property.</param>
        public static Journal CreateJournal(global::System.Int32 journalId)
        {
            Journal journal = new Journal();
            journal.JournalId = journalId;
            return journal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JournalId
        {
            get
            {
                return _JournalId;
            }
            set
            {
                if (_JournalId != value)
                {
                    OnJournalIdChanging(value);
                    ReportPropertyChanging("JournalId");
                    _JournalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JournalId");
                    OnJournalIdChanged();
                }
            }
        }
        private global::System.Int32 _JournalId;
        partial void OnJournalIdChanging(global::System.Int32 value);
        partial void OnJournalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JournalName
        {
            get
            {
                return _JournalName;
            }
            set
            {
                OnJournalNameChanging(value);
                ReportPropertyChanging("JournalName");
                _JournalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JournalName");
                OnJournalNameChanged();
            }
        }
        private global::System.String _JournalName;
        partial void OnJournalNameChanging(global::System.String value);
        partial void OnJournalNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExternalURL
        {
            get
            {
                return _ExternalURL;
            }
            set
            {
                OnExternalURLChanging(value);
                ReportPropertyChanging("ExternalURL");
                _ExternalURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExternalURL");
                OnExternalURLChanged();
            }
        }
        private global::System.String _ExternalURL;
        partial void OnExternalURLChanging(global::System.String value);
        partial void OnExternalURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "fk_Source_Journal", "Source")]
        public EntityCollection<Source> Sources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Source>("IN3LP_TestModel.fk_Source_Journal", "Source");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Source>("IN3LP_TestModel.fk_Source_Journal", "Source", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN3LP_TestModel", Name="Source")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Source : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Source object.
        /// </summary>
        /// <param name="sourceId">Initial value of the SourceId property.</param>
        /// <param name="proquestId">Initial value of the ProquestId property.</param>
        /// <param name="iSIKey">Initial value of the ISIKey property.</param>
        public static Source CreateSource(global::System.Int32 sourceId, global::System.Int32 proquestId, global::System.Int32 iSIKey)
        {
            Source source = new Source();
            source.SourceId = sourceId;
            source.ProquestId = proquestId;
            source.ISIKey = iSIKey;
            return source;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SourceId
        {
            get
            {
                return _SourceId;
            }
            set
            {
                if (_SourceId != value)
                {
                    OnSourceIdChanging(value);
                    ReportPropertyChanging("SourceId");
                    _SourceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SourceId");
                    OnSourceIdChanged();
                }
            }
        }
        private global::System.Int32 _SourceId;
        partial void OnSourceIdChanging(global::System.Int32 value);
        partial void OnSourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sourcetype
        {
            get
            {
                return _Sourcetype;
            }
            set
            {
                OnSourcetypeChanging(value);
                ReportPropertyChanging("Sourcetype");
                _Sourcetype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sourcetype");
                OnSourcetypeChanged();
            }
        }
        private global::System.String _Sourcetype;
        partial void OnSourcetypeChanging(global::System.String value);
        partial void OnSourcetypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProquestId
        {
            get
            {
                return _ProquestId;
            }
            set
            {
                OnProquestIdChanging(value);
                ReportPropertyChanging("ProquestId");
                _ProquestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProquestId");
                OnProquestIdChanged();
            }
        }
        private global::System.Int32 _ProquestId;
        partial void OnProquestIdChanging(global::System.Int32 value);
        partial void OnProquestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ISIKey
        {
            get
            {
                return _ISIKey;
            }
            set
            {
                OnISIKeyChanging(value);
                ReportPropertyChanging("ISIKey");
                _ISIKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISIKey");
                OnISIKeyChanged();
            }
        }
        private global::System.Int32 _ISIKey;
        partial void OnISIKeyChanging(global::System.Int32 value);
        partial void OnISIKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleTitle
        {
            get
            {
                return _ArticleTitle;
            }
            set
            {
                OnArticleTitleChanging(value);
                ReportPropertyChanging("ArticleTitle");
                _ArticleTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleTitle");
                OnArticleTitleChanged();
            }
        }
        private global::System.String _ArticleTitle;
        partial void OnArticleTitleChanging(global::System.String value);
        partial void OnArticleTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookTitle
        {
            get
            {
                return _BookTitle;
            }
            set
            {
                OnBookTitleChanging(value);
                ReportPropertyChanging("BookTitle");
                _BookTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BookTitle");
                OnBookTitleChanged();
            }
        }
        private global::System.String _BookTitle;
        partial void OnBookTitleChanging(global::System.String value);
        partial void OnBookTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISSN
        {
            get
            {
                return _ISSN;
            }
            set
            {
                OnISSNChanging(value);
                ReportPropertyChanging("ISSN");
                _ISSN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISSN");
                OnISSNChanged();
            }
        }
        private global::System.String _ISSN;
        partial void OnISSNChanging(global::System.String value);
        partial void OnISSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDS
        {
            get
            {
                return _IDS;
            }
            set
            {
                OnIDSChanging(value);
                ReportPropertyChanging("IDS");
                _IDS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDS");
                OnIDSChanged();
            }
        }
        private global::System.String _IDS;
        partial void OnIDSChanging(global::System.String value);
        partial void OnIDSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private Nullable<global::System.Int32> _Year;
        partial void OnYearChanging(Nullable<global::System.Int32> value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Edition
        {
            get
            {
                return _Edition;
            }
            set
            {
                OnEditionChanging(value);
                ReportPropertyChanging("Edition");
                _Edition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Edition");
                OnEditionChanged();
            }
        }
        private global::System.String _Edition;
        partial void OnEditionChanging(global::System.String value);
        partial void OnEditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.String _Volume;
        partial void OnVolumeChanging(global::System.String value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Issue
        {
            get
            {
                return _Issue;
            }
            set
            {
                OnIssueChanging(value);
                ReportPropertyChanging("Issue");
                _Issue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Issue");
                OnIssueChanged();
            }
        }
        private global::System.String _Issue;
        partial void OnIssueChanging(global::System.String value);
        partial void OnIssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpecialIssues
        {
            get
            {
                return _SpecialIssues;
            }
            set
            {
                OnSpecialIssuesChanging(value);
                ReportPropertyChanging("SpecialIssues");
                _SpecialIssues = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpecialIssues");
                OnSpecialIssuesChanged();
            }
        }
        private global::System.String _SpecialIssues;
        partial void OnSpecialIssuesChanging(global::System.String value);
        partial void OnSpecialIssuesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Publisher
        {
            get
            {
                return _Publisher;
            }
            set
            {
                OnPublisherChanging(value);
                ReportPropertyChanging("Publisher");
                _Publisher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Publisher");
                OnPublisherChanged();
            }
        }
        private global::System.String _Publisher;
        partial void OnPublisherChanging(global::System.String value);
        partial void OnPublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pages
        {
            get
            {
                return _Pages;
            }
            set
            {
                OnPagesChanging(value);
                ReportPropertyChanging("Pages");
                _Pages = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pages");
                OnPagesChanged();
            }
        }
        private global::System.String _Pages;
        partial void OnPagesChanging(global::System.String value);
        partial void OnPagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocumentType
        {
            get
            {
                return _DocumentType;
            }
            set
            {
                OnDocumentTypeChanging(value);
                ReportPropertyChanging("DocumentType");
                _DocumentType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DocumentType");
                OnDocumentTypeChanged();
            }
        }
        private global::System.String _DocumentType;
        partial void OnDocumentTypeChanging(global::System.String value);
        partial void OnDocumentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocationOfText
        {
            get
            {
                return _LocationOfText;
            }
            set
            {
                OnLocationOfTextChanging(value);
                ReportPropertyChanging("LocationOfText");
                _LocationOfText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocationOfText");
                OnLocationOfTextChanged();
            }
        }
        private global::System.String _LocationOfText;
        partial void OnLocationOfTextChanging(global::System.String value);
        partial void OnLocationOfTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocationOfPdf
        {
            get
            {
                return _LocationOfPdf;
            }
            set
            {
                OnLocationOfPdfChanging(value);
                ReportPropertyChanging("LocationOfPdf");
                _LocationOfPdf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocationOfPdf");
                OnLocationOfPdfChanged();
            }
        }
        private global::System.String _LocationOfPdf;
        partial void OnLocationOfPdfChanging(global::System.String value);
        partial void OnLocationOfPdfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExternalURL
        {
            get
            {
                return _ExternalURL;
            }
            set
            {
                OnExternalURLChanging(value);
                ReportPropertyChanging("ExternalURL");
                _ExternalURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExternalURL");
                OnExternalURLChanged();
            }
        }
        private global::System.String _ExternalURL;
        partial void OnExternalURLChanging(global::System.String value);
        partial void OnExternalURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReferencesNum
        {
            get
            {
                return _ReferencesNum;
            }
            set
            {
                OnReferencesNumChanging(value);
                ReportPropertyChanging("ReferencesNum");
                _ReferencesNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReferencesNum");
                OnReferencesNumChanged();
            }
        }
        private Nullable<global::System.Int32> _ReferencesNum;
        partial void OnReferencesNumChanging(Nullable<global::System.Int32> value);
        partial void OnReferencesNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CitedNum
        {
            get
            {
                return _CitedNum;
            }
            set
            {
                OnCitedNumChanging(value);
                ReportPropertyChanging("CitedNum");
                _CitedNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CitedNum");
                OnCitedNumChanged();
            }
        }
        private Nullable<global::System.Int32> _CitedNum;
        partial void OnCitedNumChanging(Nullable<global::System.Int32> value);
        partial void OnCitedNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private global::System.String _TimeStamp;
        partial void OnTimeStampChanging(global::System.String value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Abstract
        {
            get
            {
                return _Abstract;
            }
            set
            {
                OnAbstractChanging(value);
                ReportPropertyChanging("Abstract");
                _Abstract = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Abstract");
                OnAbstractChanged();
            }
        }
        private global::System.String _Abstract;
        partial void OnAbstractChanging(global::System.String value);
        partial void OnAbstractChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DocumentDownloadAttempted
        {
            get
            {
                return _DocumentDownloadAttempted;
            }
            set
            {
                OnDocumentDownloadAttemptedChanging(value);
                ReportPropertyChanging("DocumentDownloadAttempted");
                _DocumentDownloadAttempted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DocumentDownloadAttempted");
                OnDocumentDownloadAttemptedChanged();
            }
        }
        private Nullable<global::System.Boolean> _DocumentDownloadAttempted;
        partial void OnDocumentDownloadAttemptedChanging(Nullable<global::System.Boolean> value);
        partial void OnDocumentDownloadAttemptedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JournalId
        {
            get
            {
                return _JournalId;
            }
            set
            {
                OnJournalIdChanging(value);
                ReportPropertyChanging("JournalId");
                _JournalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JournalId");
                OnJournalIdChanged();
            }
        }
        private Nullable<global::System.Int32> _JournalId;
        partial void OnJournalIdChanging(Nullable<global::System.Int32> value);
        partial void OnJournalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                OnAuthorIdChanging(value);
                ReportPropertyChanging("AuthorId");
                _AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorId");
                OnAuthorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AuthorId;
        partial void OnAuthorIdChanging(Nullable<global::System.Int32> value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EditorId
        {
            get
            {
                return _EditorId;
            }
            set
            {
                OnEditorIdChanging(value);
                ReportPropertyChanging("EditorId");
                _EditorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditorId");
                OnEditorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EditorId;
        partial void OnEditorIdChanging(Nullable<global::System.Int32> value);
        partial void OnEditorIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "fk_Source_Author", "Author")]
        public Author Author
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("IN3LP_TestModel.fk_Source_Author", "Author").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("IN3LP_TestModel.fk_Source_Author", "Author").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Author> AuthorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("IN3LP_TestModel.fk_Source_Author", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Author>("IN3LP_TestModel.fk_Source_Author", "Author", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "fk_Source_Editor", "Editor")]
        public Editor Editor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Editor>("IN3LP_TestModel.fk_Source_Editor", "Editor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Editor>("IN3LP_TestModel.fk_Source_Editor", "Editor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Editor> EditorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Editor>("IN3LP_TestModel.fk_Source_Editor", "Editor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Editor>("IN3LP_TestModel.fk_Source_Editor", "Editor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "fk_Source_Journal", "Journal")]
        public Journal Journal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Journal>("IN3LP_TestModel.fk_Source_Journal", "Journal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Journal>("IN3LP_TestModel.fk_Source_Journal", "Journal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Journal> JournalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Journal>("IN3LP_TestModel.fk_Source_Journal", "Journal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Journal>("IN3LP_TestModel.fk_Source_Journal", "Journal", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "CitationReference", "Source1")]
        public EntityCollection<Source> Source1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Source>("IN3LP_TestModel.CitationReference", "Source1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Source>("IN3LP_TestModel.CitationReference", "Source1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IN3LP_TestModel", "CitationReference", "Source")]
        public EntityCollection<Source> Sources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Source>("IN3LP_TestModel.CitationReference", "Source");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Source>("IN3LP_TestModel.CitationReference", "Source", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
