//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATN.Crawler.WokSearchLite {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class InternalServerException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class labelValuesPair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class liteRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private labelValuesPair[] authorsField;
        
        private labelValuesPair[] keywordsField;
        
        private labelValuesPair[] otherField;
        
        private labelValuesPair[] sourceField;
        
        private labelValuesPair[] titleField;
        
        private string utField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public labelValuesPair[] authors {
            get {
                return this.authorsField;
            }
            set {
                this.authorsField = value;
                this.RaisePropertyChanged("authors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public labelValuesPair[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
                this.RaisePropertyChanged("keywords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("other", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public labelValuesPair[] other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
                this.RaisePropertyChanged("other");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("source", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public labelValuesPair[] source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public labelValuesPair[] title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UT {
            get {
                return this.utField;
            }
            set {
                this.utField = value;
                this.RaisePropertyChanged("UT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class searchResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private liteRecord parentField;
        
        private string queryIDField;
        
        private liteRecord[] recordsField;
        
        private int recordsFoundField;
        
        private long recordsSearchedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public liteRecord parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
                this.RaisePropertyChanged("parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string queryID {
            get {
                return this.queryIDField;
            }
            set {
                this.queryIDField = value;
                this.RaisePropertyChanged("queryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public liteRecord[] records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int recordsFound {
            get {
                return this.recordsFoundField;
            }
            set {
                this.recordsFoundField = value;
                this.RaisePropertyChanged("recordsFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long recordsSearched {
            get {
                return this.recordsSearchedField;
            }
            set {
                this.recordsSearchedField = value;
                this.RaisePropertyChanged("recordsSearched");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class queryField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string sortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
                this.RaisePropertyChanged("sort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class retrieveParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private queryField[] fieldsField;
        
        private int firstRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public queryField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int firstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                this.firstRecordField = value;
                this.RaisePropertyChanged("firstRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class InvalidInputException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class ESTIWSException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class AuthenticationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class QueryException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class SessionException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", ConfigurationName="WokSearchLite.WokSearchLite")]
    public interface WokSearchLite {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearchLite.retrieveByIdResponse retrieveById(ATN.Crawler.WokSearchLite.retrieveById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.retrieveByIdResponse> retrieveByIdAsync(ATN.Crawler.WokSearchLite.retrieveById request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearchLite.retrieveResponse retrieve(ATN.Crawler.WokSearchLite.retrieve request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.retrieveResponse> retrieveAsync(ATN.Crawler.WokSearchLite.retrieve request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearchLite.searchResponse search(ATN.Crawler.WokSearchLite.search request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.searchResponse> searchAsync(ATN.Crawler.WokSearchLite.search request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearchLite.citingArticlesResponse citingArticles(ATN.Crawler.WokSearchLite.citingArticles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.citingArticlesResponse> citingArticlesAsync(ATN.Crawler.WokSearchLite.citingArticles request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WokSearchLite.SessionException), Action="", Name="SessionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ATN.Crawler.WokSearchLite.relatedRecordsResponse relatedRecords(ATN.Crawler.WokSearchLite.relatedRecords request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.relatedRecordsResponse> relatedRecordsAsync(ATN.Crawler.WokSearchLite.relatedRecords request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveById", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieveById {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("uids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] uids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters;
        
        public retrieveById() {
        }
        
        public retrieveById(string databaseId, string[] uids, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uids = uids;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveByIdResponse", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieveByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.searchResults @return;
        
        public retrieveByIdResponse() {
        }
        
        public retrieveByIdResponse(ATN.Crawler.WokSearchLite.searchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieve", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieve {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters;
        
        public retrieve() {
        }
        
        public retrieve(string queryId, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            this.queryId = queryId;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveResponse", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class retrieveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.searchResults @return;
        
        public retrieveResponse() {
        }
        
        public retrieveResponse(ATN.Crawler.WokSearchLite.searchResults @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class queryParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string databaseIDField;
        
        private editionDesc[] editionsField;
        
        private string queryLanguageField;
        
        private string symbolicTimeSpanField;
        
        private timeSpan timeSpanField;
        
        private string userQueryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string databaseID {
            get {
                return this.databaseIDField;
            }
            set {
                this.databaseIDField = value;
                this.RaisePropertyChanged("databaseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("editions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public editionDesc[] editions {
            get {
                return this.editionsField;
            }
            set {
                this.editionsField = value;
                this.RaisePropertyChanged("editions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string queryLanguage {
            get {
                return this.queryLanguageField;
            }
            set {
                this.queryLanguageField = value;
                this.RaisePropertyChanged("queryLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string symbolicTimeSpan {
            get {
                return this.symbolicTimeSpanField;
            }
            set {
                this.symbolicTimeSpanField = value;
                this.RaisePropertyChanged("symbolicTimeSpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public timeSpan timeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("timeSpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userQuery {
            get {
                return this.userQueryField;
            }
            set {
                this.userQueryField = value;
                this.RaisePropertyChanged("userQuery");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class editionDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string collectionField;
        
        private string editionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string collection {
            get {
                return this.collectionField;
            }
            set {
                this.collectionField = value;
                this.RaisePropertyChanged("collection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
                this.RaisePropertyChanged("edition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com")]
    public partial class timeSpan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string beginField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
                this.RaisePropertyChanged("begin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="search", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class search {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.queryParameters queryParameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters;
        
        public search() {
        }
        
        public search(ATN.Crawler.WokSearchLite.queryParameters queryParameters, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            this.queryParameters = queryParameters;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchResponse", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class searchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.searchResults @return;
        
        public searchResponse() {
        }
        
        public searchResponse(ATN.Crawler.WokSearchLite.searchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citingArticles", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citingArticles {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("editionDesc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.editionDesc[] editionDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.timeSpan timeSpan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters;
        
        public citingArticles() {
        }
        
        public citingArticles(string databaseId, string uid, ATN.Crawler.WokSearchLite.editionDesc[] editionDesc, ATN.Crawler.WokSearchLite.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uid = uid;
            this.editionDesc = editionDesc;
            this.timeSpan = timeSpan;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="citingArticlesResponse", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class citingArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.searchResults @return;
        
        public citingArticlesResponse() {
        }
        
        public citingArticlesResponse(ATN.Crawler.WokSearchLite.searchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="relatedRecords", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class relatedRecords {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string databaseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("editionDesc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.editionDesc[] editionDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.timeSpan timeSpan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters;
        
        public relatedRecords() {
        }
        
        public relatedRecords(string databaseId, string uid, ATN.Crawler.WokSearchLite.editionDesc[] editionDesc, ATN.Crawler.WokSearchLite.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            this.databaseId = databaseId;
            this.uid = uid;
            this.editionDesc = editionDesc;
            this.timeSpan = timeSpan;
            this.queryLanguage = queryLanguage;
            this.retrieveParameters = retrieveParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="relatedRecordsResponse", WrapperNamespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", IsWrapped=true)]
    public partial class relatedRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://woksearchlite.cxf.wokmws.thomsonreuters.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATN.Crawler.WokSearchLite.searchResults @return;
        
        public relatedRecordsResponse() {
        }
        
        public relatedRecordsResponse(ATN.Crawler.WokSearchLite.searchResults @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WokSearchLiteChannel : ATN.Crawler.WokSearchLite.WokSearchLite, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WokSearchLiteClient : System.ServiceModel.ClientBase<ATN.Crawler.WokSearchLite.WokSearchLite>, ATN.Crawler.WokSearchLite.WokSearchLite {
        
        public WokSearchLiteClient() {
        }
        
        public WokSearchLiteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WokSearchLiteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WokSearchLiteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WokSearchLiteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearchLite.retrieveByIdResponse ATN.Crawler.WokSearchLite.WokSearchLite.retrieveById(ATN.Crawler.WokSearchLite.retrieveById request) {
            return base.Channel.retrieveById(request);
        }
        
        public ATN.Crawler.WokSearchLite.searchResults retrieveById(string databaseId, string[] uids, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.retrieveById inValue = new ATN.Crawler.WokSearchLite.retrieveById();
            inValue.databaseId = databaseId;
            inValue.uids = uids;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearchLite.retrieveByIdResponse retVal = ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).retrieveById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.retrieveByIdResponse> ATN.Crawler.WokSearchLite.WokSearchLite.retrieveByIdAsync(ATN.Crawler.WokSearchLite.retrieveById request) {
            return base.Channel.retrieveByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.retrieveByIdResponse> retrieveByIdAsync(string databaseId, string[] uids, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.retrieveById inValue = new ATN.Crawler.WokSearchLite.retrieveById();
            inValue.databaseId = databaseId;
            inValue.uids = uids;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).retrieveByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearchLite.retrieveResponse ATN.Crawler.WokSearchLite.WokSearchLite.retrieve(ATN.Crawler.WokSearchLite.retrieve request) {
            return base.Channel.retrieve(request);
        }
        
        public ATN.Crawler.WokSearchLite.searchResults retrieve(string queryId, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.retrieve inValue = new ATN.Crawler.WokSearchLite.retrieve();
            inValue.queryId = queryId;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearchLite.retrieveResponse retVal = ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).retrieve(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.retrieveResponse> ATN.Crawler.WokSearchLite.WokSearchLite.retrieveAsync(ATN.Crawler.WokSearchLite.retrieve request) {
            return base.Channel.retrieveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.retrieveResponse> retrieveAsync(string queryId, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.retrieve inValue = new ATN.Crawler.WokSearchLite.retrieve();
            inValue.queryId = queryId;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).retrieveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearchLite.searchResponse ATN.Crawler.WokSearchLite.WokSearchLite.search(ATN.Crawler.WokSearchLite.search request) {
            return base.Channel.search(request);
        }
        
        public ATN.Crawler.WokSearchLite.searchResults search(ATN.Crawler.WokSearchLite.queryParameters queryParameters, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.search inValue = new ATN.Crawler.WokSearchLite.search();
            inValue.queryParameters = queryParameters;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearchLite.searchResponse retVal = ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).search(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.searchResponse> ATN.Crawler.WokSearchLite.WokSearchLite.searchAsync(ATN.Crawler.WokSearchLite.search request) {
            return base.Channel.searchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.searchResponse> searchAsync(ATN.Crawler.WokSearchLite.queryParameters queryParameters, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.search inValue = new ATN.Crawler.WokSearchLite.search();
            inValue.queryParameters = queryParameters;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).searchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearchLite.citingArticlesResponse ATN.Crawler.WokSearchLite.WokSearchLite.citingArticles(ATN.Crawler.WokSearchLite.citingArticles request) {
            return base.Channel.citingArticles(request);
        }
        
        public ATN.Crawler.WokSearchLite.searchResults citingArticles(string databaseId, string uid, ATN.Crawler.WokSearchLite.editionDesc[] editionDesc, ATN.Crawler.WokSearchLite.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.citingArticles inValue = new ATN.Crawler.WokSearchLite.citingArticles();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editionDesc = editionDesc;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearchLite.citingArticlesResponse retVal = ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).citingArticles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.citingArticlesResponse> ATN.Crawler.WokSearchLite.WokSearchLite.citingArticlesAsync(ATN.Crawler.WokSearchLite.citingArticles request) {
            return base.Channel.citingArticlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.citingArticlesResponse> citingArticlesAsync(string databaseId, string uid, ATN.Crawler.WokSearchLite.editionDesc[] editionDesc, ATN.Crawler.WokSearchLite.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.citingArticles inValue = new ATN.Crawler.WokSearchLite.citingArticles();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editionDesc = editionDesc;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).citingArticlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WokSearchLite.relatedRecordsResponse ATN.Crawler.WokSearchLite.WokSearchLite.relatedRecords(ATN.Crawler.WokSearchLite.relatedRecords request) {
            return base.Channel.relatedRecords(request);
        }
        
        public ATN.Crawler.WokSearchLite.searchResults relatedRecords(string databaseId, string uid, ATN.Crawler.WokSearchLite.editionDesc[] editionDesc, ATN.Crawler.WokSearchLite.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.relatedRecords inValue = new ATN.Crawler.WokSearchLite.relatedRecords();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editionDesc = editionDesc;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            ATN.Crawler.WokSearchLite.relatedRecordsResponse retVal = ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).relatedRecords(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.relatedRecordsResponse> ATN.Crawler.WokSearchLite.WokSearchLite.relatedRecordsAsync(ATN.Crawler.WokSearchLite.relatedRecords request) {
            return base.Channel.relatedRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WokSearchLite.relatedRecordsResponse> relatedRecordsAsync(string databaseId, string uid, ATN.Crawler.WokSearchLite.editionDesc[] editionDesc, ATN.Crawler.WokSearchLite.timeSpan timeSpan, string queryLanguage, ATN.Crawler.WokSearchLite.retrieveParameters retrieveParameters) {
            ATN.Crawler.WokSearchLite.relatedRecords inValue = new ATN.Crawler.WokSearchLite.relatedRecords();
            inValue.databaseId = databaseId;
            inValue.uid = uid;
            inValue.editionDesc = editionDesc;
            inValue.timeSpan = timeSpan;
            inValue.queryLanguage = queryLanguage;
            inValue.retrieveParameters = retrieveParameters;
            return ((ATN.Crawler.WokSearchLite.WokSearchLite)(this)).relatedRecordsAsync(inValue);
        }
    }
}
