//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATN.Crawler.WOKMWSAuthenticate {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternalServerException", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
    [System.SerializableAttribute()]
    public partial class InternalServerException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidInputException", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
    [System.SerializableAttribute()]
    public partial class InvalidInputException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESTIWSException", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
    [System.SerializableAttribute()]
    public partial class ESTIWSException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationException", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
    [System.SerializableAttribute()]
    public partial class AuthenticationException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryException", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
    [System.SerializableAttribute()]
    public partial class QueryException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionException", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
    [System.SerializableAttribute()]
    public partial class SessionException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://auth.cxf.wokmws.thomsonreuters.com", ConfigurationName="WOKMWSAuthenticate.WOKMWSAuthenticate")]
    public interface WOKMWSAuthenticate {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.SessionException), Action="", Name="SessionException")]
        ATN.Crawler.WOKMWSAuthenticate.authenticateResponse authenticate(ATN.Crawler.WOKMWSAuthenticate.authenticate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ATN.Crawler.WOKMWSAuthenticate.authenticateResponse> authenticateAsync(ATN.Crawler.WOKMWSAuthenticate.authenticate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.InvalidInputException), Action="", Name="InvalidInputException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.ESTIWSException), Action="", Name="ESTIWSException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.AuthenticationException), Action="", Name="AuthenticationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.QueryException), Action="", Name="QueryException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATN.Crawler.WOKMWSAuthenticate.SessionException), Action="", Name="SessionException")]
        void closeSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task closeSessionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticate", Namespace="http://auth.cxf.wokmws.thomsonreuters.com", Order=0)]
        public ATN.Crawler.WOKMWSAuthenticate.authenticateBody Body;
        
        public authenticate() {
        }
        
        public authenticate(ATN.Crawler.WOKMWSAuthenticate.authenticateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class authenticateBody {
        
        public authenticateBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateResponse", Namespace="http://auth.cxf.wokmws.thomsonreuters.com", Order=0)]
        public ATN.Crawler.WOKMWSAuthenticate.authenticateResponseBody Body;
        
        public authenticateResponse() {
        }
        
        public authenticateResponse(ATN.Crawler.WOKMWSAuthenticate.authenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class authenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public authenticateResponseBody() {
        }
        
        public authenticateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WOKMWSAuthenticateChannel : ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WOKMWSAuthenticateClient : System.ServiceModel.ClientBase<ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate>, ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate {
        
        public WOKMWSAuthenticateClient() {
        }
        
        public WOKMWSAuthenticateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WOKMWSAuthenticateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WOKMWSAuthenticateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WOKMWSAuthenticateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATN.Crawler.WOKMWSAuthenticate.authenticateResponse ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate.authenticate(ATN.Crawler.WOKMWSAuthenticate.authenticate request) {
            return base.Channel.authenticate(request);
        }
        
        public string authenticate() {
            ATN.Crawler.WOKMWSAuthenticate.authenticate inValue = new ATN.Crawler.WOKMWSAuthenticate.authenticate();
            inValue.Body = new ATN.Crawler.WOKMWSAuthenticate.authenticateBody();
            ATN.Crawler.WOKMWSAuthenticate.authenticateResponse retVal = ((ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate)(this)).authenticate(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ATN.Crawler.WOKMWSAuthenticate.authenticateResponse> ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate.authenticateAsync(ATN.Crawler.WOKMWSAuthenticate.authenticate request) {
            return base.Channel.authenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ATN.Crawler.WOKMWSAuthenticate.authenticateResponse> authenticateAsync() {
            ATN.Crawler.WOKMWSAuthenticate.authenticate inValue = new ATN.Crawler.WOKMWSAuthenticate.authenticate();
            inValue.Body = new ATN.Crawler.WOKMWSAuthenticate.authenticateBody();
            return ((ATN.Crawler.WOKMWSAuthenticate.WOKMWSAuthenticate)(this)).authenticateAsync(inValue);
        }
        
        public void closeSession() {
            base.Channel.closeSession();
        }
        
        public System.Threading.Tasks.Task closeSessionAsync() {
            return base.Channel.closeSessionAsync();
        }
    }
}
